# Root path for the suites/playlists
# Relative paths are relative to the config file location
playlist-root = "."

[plai]

# Unix socket where to reach plai
socket = "/tmp/plai.sock"


# Set to true to start plai as a subprocess
# If false plai is managed externally, e.g. via systemd
run = false

# Plai command. Either a program name in path or path to the executable
# This is only used if plai is started by mplayer.
path = "plai"

# Path where plai places sqlite database
db = ":memory:"

# Log level
log-level = "info"

# Whether to fullscreen
fullscreen = false

# Image duration in seconds
image-duration = 1.0

# Blend duration when switching from one media to another
blend-duration = 1.0

[plai.watermark]
# Path to watermark to render to the screen
path = ""

# How to scale the watermark
#
# This changes behavior depending how the watermark is configured.
# If non-stretching scaling is enabled this is the max size in
# relation to viewport dimensions.
scaling = { w = 1.0, h = 1.0}

# Watermark placement as "<vertical>-<horizontal>"
# Vertical is one of (top, middle, bottom)
# Horizontal is one of (left, middle, right)
position = "bottom-middle"


# Playlist is a set of media files to play
# The first variant prints the globs directly
[playlist.adds]
globs = ["Mainokset/*.mp4"]

# Filters filer the data dynamically, in this case 5 newest files are selected
[playlist.pics]
globs = "Photo/*.JPG"
filter = { algo = "newest|newer_than", count = 5,  max_age = 01:00:00 }

# The second variant adds indirection by referencing other playlists.
[playlist.wed]
from = ["prog_wed", "pics"]

[playlist.thu]
from = ["prog_thu", "pics"]

[playlist.fri]
from = ["prog_fri", "pics"]

[playlist.sat]
from = ["prog_sat", "pics"]

[playlist.prog_wed]
globs = "Ohjelma/Ke/*.mp4"

[playlist.prog_thu]
globs = "Ohjelma/To/*.mp4"

[playlist.prog_fri]
globs = "Ohjelma/Pe/*.mp4"

[playlist.prog_sat]
globs = "Ohjelma/La/*.mp4"

