# List of playlists, used to protect against typos
playlist_names = ["mainokset", "kuvat"]

# Schedule of playlists
[[schedule]]
playlist = "adds"
at = 2025-06-18 00:00:00

[[schedule]]
playlist = "pics"
offset = 01:00:00

[[schedule]]
playlist = "adds"
at = "25:00:00"
